import '@/styles/global.css'

import Header from './Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen min-w-[896px]">
        <Header />
        <main className="h-[100rem]">
          {children}
        </main>
      </body>
    </html>
  )
}
